/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

var startTime = new Date();

var terms = [1,1];
var sum = 0;
var num = 0;

while(num < 4000000){
	num = terms[0] + terms[1];
	terms.push(num);
	terms.shift();
	if(num % 2 === 0)
		sum += num;
}


console.log(sum);
console.log("Elapsed Time: " + (new Date() - startTime) / 1000 +" s");